# Generated by Django 4.0.5 on 2022-07-03 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='имя')),
                ('patronymic', models.CharField(db_index=True, max_length=50, verbose_name='отчество')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, verbose_name='email')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='контактный телефон')),
                ('date_of_birth', models.DateField(db_index=True, verbose_name='дата рождения')),
                ('passport', models.CharField(db_index=True, max_length=20, verbose_name='серия и номер паспорта')),
                ('address', models.CharField(db_index=True, max_length=150, verbose_name='адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
