# Generated by Django 4.0.5 on 2022-07-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='qr_code',
        ),
    ]
