# Generated by Django 4.0.5 on 2022-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nais_storage', '0004_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='storage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='долгота'),
        ),
    ]
